"""empty message

Revision ID: 9dceb4393e77
Revises: 2e166c75ba68
Create Date: 2023-11-04 23:12:01.335384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dceb4393e77'
down_revision: Union[str, None] = '2e166c75ba68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email1', table_name='users')
    op.drop_column('users', 'email1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email1', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_email1', 'users', ['email1'], unique=False)
    # ### end Alembic commands ###
