version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: fast_api_celery_web_2
    command: ["uvicorn", "main:app" ,"--reload", "--host", "0.0.0.0"]
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - 8010:8000
   
    depends_on:
      - redis
      - db

  
  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    image: fastapi_celery_celery_worker_2
    command: ["celery", "-A" ,"main.celery" ,"worker", "--loglevel=debug"]
    volumes:
      - .:/app
    env_file:
      - .env.dev
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: fastapi_celery_celery_flower_2
    command: /start_flower.sh
    volumes:
      - .:/app
    env_file:
      - .env.dev
    ports:
      - 5550:5555
    depends_on:
      - redis

  db:
    image: postgres:12
    volumes:
      - postgres_data6:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname

volumes:
  postgres_data6: