FROM python:3.10-slim-buster

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# RUN apt-get update \
#   # dependencies for building Python packages
#   && apt-get install -y build-essential \
#   # psycopg2 dependencies
#   && apt-get install -y libpq-dev \
#   # Additional dependencies
#   && apt-get install -y telnet netcat \
#   # cleaning up unused files
#   && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
#   && rm -rf /var/lib/apt/lists/*

# Requirements are installed here to ensure they will be cached.
RUN  apt-get update && apt-get install -y  python-psycopg2
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
WORKDIR /app
COPY scripts/start_flower.sh /start_flower.sh
RUN chmod +x /start_flower.sh
# in dev we dont copy the source code
# CMD ["uvicorn", "main:app" ,"--reload", "--host", "0.0.0.0"]