"""empty message

Revision ID: b3a5395760e4
Revises: 04ae9e8fcd19
Create Date: 2023-11-05 23:29:35.365004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a5395760e4'
down_revision: Union[str, None] = '04ae9e8fcd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatrooms_id'), 'chatrooms', ['id'], unique=False)
    op.create_index(op.f('ix_chatrooms_name'), 'chatrooms', ['name'], unique=False)
    op.create_table('chatroom_member',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chatroom_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatrooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.drop_column('users', 'sec')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sec', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('chatroom_member')
    op.drop_index(op.f('ix_chatrooms_name'), table_name='chatrooms')
    op.drop_index(op.f('ix_chatrooms_id'), table_name='chatrooms')
    op.drop_table('chatrooms')
    # ### end Alembic commands ###
